AWSTemplateFormatVersion: "2010-09-09"

Metadata:
  License: Apache-2.0

Description: "CloudFormation template for CloudAdmin onboarding. This will create an IAM role, custom policy apply that to the IAM role, and also give the IAM role the proper read only policy for the cost & usage report."

Parameters:

  S3BucketName:
    Type: String
    Description: S3 bucket name where the S3 Policy will be applied to.
    Default: <New Bucket>
    AllowedPattern: ".+"

Resources:

  CloudAdminUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Join [ "_", [ "CloudAdminIAM", !Ref "AWS::StackName" ] ]

  CloudAdminIAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudAdminIAMPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - cloudwatch:Describe*
              - cloudwatch:Get*
              - cloudwatch:List*
              - ec2:DeleteSnapshot
              - ec2:DeleteVolume
              - ec2:Describe*
              - ec2:PurchaseReservedInstancesOffering
              - ec2:ReleaseAddress
              - ec2:StartInstances
              - ec2:StopInstances
              - elasticache:Describe*
              - elasticache:ListTagsForResource
              - elasticache:PurchaseReservedCacheNodesOffering
              - elasticloadbalancing:DeleteLoadBalancer
              - elasticloadbalancing:Describe*
              - es:Describe*
              - es:ListDomainNames
              - es:ListTags
              - es:PurchaseReservedElasticsearchInstanceOffering
              - rds:DeleteDBSnapshot
              - rds:Describe*
              - rds:ListTagsForResource
              - rds:PurchaseReservedDBInstancesOffering
              - rds:StartDBInstance
              - rds:StopDBInstance
              - redshift:Describe*
              - redshift:PauseCluster
              - redshift:PurchaseReservedNodeOffering
              - redshift:ResumeCluster
              - savingsplans:CreateSavingsPlan
              - savingsplans:Describe*
              - sts:GetCallerIdentity
            Resource: "*"
      Users:
        - !Ref "CloudAdminUser"

  CloudAdminS3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudAdminS3Policy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource: !Sub "arn:aws:s3:::${S3BucketName}"
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
            Resource: !Sub "arn:aws:s3:::${S3BucketName}/*"
      Users:
        - !Ref "CloudAdminUser"
  CloudAdminKeys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref "CloudAdminUser"

Outputs:

  AccessKey:
    Value: !Ref "CloudAdminKeys"
    Description: AWSAccessKeyId of new user

  SecretKey:
    Value: !GetAtt [ CloudAdminKeys, SecretAccessKey ]
    Description: AWSSecretAccessKey of new user
