AWSTemplateFormatVersion: "2010-09-09"

Metadata:
  License: Apache-2.0

Description: "CloudFormation template for CloudAdmin onboarding for users using AWS Organizations. This will create an IAM role, custom policy apply that to the IAM role, and also give the IAM role the proper read only policy for the cost & usage report."

Parameters:

  S3BucketName:
    Type: String
    Description: New S3 bucket name for creation.
    AllowedPattern: ".+"
    MinLength: 1
    Default: <cloudadmin-companyname-billing>

Resources:

  CloudAdminUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Join [ "_", [ "CloudAdminOrganizationIAM", !Ref "AWS::StackName" ] ]

  CloudAdminKeys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref "CloudAdminUser"

  CloudAdminS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: BucketOwnerRead

  CloudAdminBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudAdminS3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: billingreports.amazonaws.com
            Action:
              - s3:GetBucketAcl
              - s3:GetBucketPolicy
            Resource: !Sub "arn:aws:s3:::${CloudAdminS3Bucket}"
          - Effect: Allow
            Principal:
              Service: billingreports.amazonaws.com
            Action:
              - s3:PutObject
            Resource: !Sub "arn:aws:s3:::${CloudAdminS3Bucket}/*"

  CloudAdminOrganizationIAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudAdminOrganizationIAMPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - organizations:ListAccounts
              - sts:AssumeRole
              - sts:GetCallerIdentity
            Resource: "*"
      Users:
        - !Ref "CloudAdminUser"

  CloudAdminOrganizationS3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudAdminOrganizationS3Policy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketLocation
            Resource: !Sub "arn:aws:s3:::${CloudAdminS3Bucket}"
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
            Resource: !Sub "arn:aws:s3:::${CloudAdminS3Bucket}/*"
          - Effect: Allow
            Action:
              - cur:PutReportDefinition
            Resource: !Sub "arn:aws:cur:*:${AWS::AccountId}:definition/*"
      Users:
        - !Ref "CloudAdminUser"

  CostReportFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Creates a new daily billing usage report."
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Runtime: python3.8
      Timeout: 10
      Handler: index.lambda_handler
      Code:
        ZipFile:
          Fn::Sub: |-
            #!/usr/bin/env python3

            import boto3
            import uuid

            import cfnresponse
            import traceback

            def lambda_handler(event, context):
                access_key = event['ResourceProperties']['Input1']
                secret_key = event['ResourceProperties']['Input2']
                bucket = event['ResourceProperties']['Input3']

                location = ''

                try:
                    s3_client = boto3.client('s3', aws_access_key_id=access_key, aws_secret_access_key=secret_key)
                    location_response = s3_client.get_bucket_location(Bucket=bucket)
                    location = location_response['LocationConstraint']
                except Exception as ex:
                    print(str(ex))

                prefix = 'cloudadmin-billing'
                response_data = {'bucket': bucket, 'prefix': prefix, 'location': location}
                cur_client = boto3.client('cur', region_name='us-east-1', aws_access_key_id=access_key, aws_secret_access_key=secret_key)
                try:
                    report = cur_client.put_report_definition(
                        ReportDefinition={
                            'ReportName': f'billing-cloudadmin-{uuid.uuid4()}',
                            'TimeUnit': 'DAILY',
                            'Format': 'textORcsv',
                            'AdditionalSchemaElements': [
                                'RESOURCES'
                            ],
                            'Compression': 'GZIP',
                            'S3Bucket': bucket,
                            'S3Prefix': prefix,
                            'S3Region': location,
                        }
                    )
                except Exception as ex:
                    traceback.print_exc()
                finally:
                    cfnresponse.send(event, context, cfnresponse.SUCCESS, response_data)

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub "lambda.${AWS::URLSuffix}"
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  CostReport:
    Type: Custom::CostReport
    DependsOn:
      - "CloudAdminOrganizationS3Policy"
      - "CloudAdminS3Bucket"
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - CostReportFunction
          - Arn
      Input1:
        Ref: CloudAdminKeys
      Input2:
        Fn::GetAtt:
          - CloudAdminKeys
          - SecretAccessKey
      Input3:
        Ref: CloudAdminS3Bucket

Outputs:

  AccessKey:
    Value: !Ref "CloudAdminKeys"
    Description: AWS Access Key to be used on CloudAdmin

  SecretKey:
    Value: !GetAtt [ CloudAdminKeys, SecretAccessKey ]
    Description: AWS Secret Access Key to be used on CloudAdmin

  Bucket:
    Value: !GetAtt [ CostReport, bucket ]
    Description: Bucket name  to be used on CloudAdmin

  BucketPrefix:
    Value: !GetAtt [ CostReport, prefix ]
    Description: Bucket prefix to be used on CloudAdmin

  BucketLocation:
    Value: !GetAtt [ CostReport, location ]
    Description: Location of the bucket created
